# Generated by Django 5.1.4 on 2025-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_userprofile_is_approved_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
