# Generated by Django 5.1.4 on 2025-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_userprofile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
