# Generated by Django 5.1.4 on 2025-01-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_specialevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialEvent',
            new_name='ImportantEvent',
        ),
    ]
