# Generated by Django 5.1.4 on 2025-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_rename_specialevent_importantevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Staff', 'Staff'), ('User', 'User')], default='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='importantevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
