# Generated by Django 4.2.18 on 2025-02-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
